### ISSUE TITLE
Every preset makes 'git diff' look awful

### ISSUE THREAD

**Issue by voxelv** [lukesampson/concfg#52]
I'm not sure what I'm doing wrong, but doing a 'git diff' always seems to end up with grayscale text colors. I'd really like to see lines removed as red, lines added as green, and file information as yellow. Is there a way to get concfg to do that?

**Comment by mattb-atomic** [comment]
@h404bi Here's a screenshot. I just imported the "github" theme with `concfg import github`.

![image](https://user-images.githubusercontent.com/42125261/44344389-98120900-a45e-11e8-8d50-949bc42b287e.png)

It looks like the colors aren't applied in the proper slots or something?

I'm using concfg version 0.2018.5.27 installed from Scoop.

**Comment by h404bi** [comment]
@mattb-atomic What version of PowerShell are you using.

**Comment by mattb-atomic** [comment]
@h404bi 

```
Name                           Value
----                           -----
PSVersion                      5.1.17134.228
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.228
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by h404bi** [comment]
@mattb-atomic it seems that the `github` preset colors mapping is problematic, have you tried another preset?

**Comment by mattb-atomic** [comment]
I don't recall exactly which ones I've tried, but I've tried several.

Of note that for a theme like `solarized-light`, if you head into the properties dialog and the colors tab, you'll find the colors are arranged much like a crayon box instead of aligned according to the intended colors of each slot. This is from `solarized-light`:

![image](https://user-images.githubusercontent.com/42125261/44350865-6608a300-a46e-11e8-966a-ce8c423ac2aa.png)

With the colors in these slots, the red and green diff colors are represented with different grayscale colors, and removed lines are barely visible:

![image](https://user-images.githubusercontent.com/42125261/44350999-c13a9580-a46e-11e8-9a0c-9b12a31892e6.png)

**Comment by h404bi** [comment]
@mattb-atomic I see, I was thinking that the pull request #41 and #43 changed/made somthing wrong on the base16 colors mapping. I created a repository with some generated base16 presets.

https://github.com/h404bi/base16-concfg

I have tested `base16-solarized-light`, `base16-solarized-dark`, `base16-ocean` and others, and they works fine. I just tried my `base16-github`, and it's problematic, too. It seems that the problem is on the base16 github scheme color mapping.

Maybe you could try the presets I generated:

``` powershell
concfg clean
concfg import https://raw.githubusercontent.com/h404bi/base16-concfg/master/presets/base16-solarized-light.json
concfg tokencolor enable
```

**Comment by mattb-atomic** [comment]
Bringing in and importing your `base16-solarized-light` with the commands you listed worked; I'm seeing red and green lines appropriately in `git diff` output.

**Comment by mattb-atomic** [comment]
Of note, I missed the `concfg tokencolor enable` first time through—didn't seem I needed it. But I enabled it afterward and spawned a new window and everything's still great 👍

**Comment by h404bi** [comment]
@mattb-atomic Yes, `concfg tokencolor enable` is optional, I use it to enable the colors of powershell commandline tokens, you'll find the explanation about it on [h404bi/base16-concfg](https://github.com/h404bi/base16-concfg#about-command-line-token-colors). Glad to see that it works as expected for you.

**Comment by KrisThielemans** [comment]
https://raw.githubusercontent.com/h404bi/base16-concfg/master/presets/base16-solarized-light.json solves git problems but I now have unreadable options (anything with -)
![image](https://user-images.githubusercontent.com/6362141/59972501-40fe2880-9588-11e9-982b-a01cfa6264fb.png)

I have no clue which tokenkind this is. I set a few more and ended up with
```
ContinuationPromptForegroundColor : White
ContinuationPromptBackgroundColor : Black
DefaultTokenForegroundColor       : DarkGreen
CommentForegroundColor            : DarkGreen
KeywordForegroundColor            : DarkGreen
StringForegroundColor             : DarkGreen
OperatorForegroundColor           : DarkGreen
VariableForegroundColor           : DarkGreen
CommandForegroundColor            : DarkGreen
ParameterForegroundColor          : DarkGray
TypeForegroundColor               : DarkGreen
NumberForegroundColor             : DarkGreen
MemberForegroundColor             : DarkGray
DefaultTokenBackgroundColor       : Black
CommentBackgroundColor            : Black
KeywordBackgroundColor            : Black
StringBackgroundColor             : Black
OperatorBackgroundColor           : Black
VariableBackgroundColor           : Black
CommandBackgroundColor            : Black
ParameterBackgroundColor          : Black
TypeBackgroundColor               : Black
NumberBackgroundColor             : Black
MemberBackgroundColor             : Black
EmphasisForegroundColor           : Cyan
EmphasisBackgroundColor           : Black
ErrorForegroundColor              : Red
ErrorBackgroundColor              : Black
```
but that didn't change my problem. The color seems to be something very light gray (it isn't white).

My PS version is 5.1.17134.765

**Comment by h404bi** [comment]
@KrisThielemans All my color schemes are based on base16 architecture, and when you're using one of those themes, you may need to enable tokencolor correction to change token colors (see https://github.com/h404bi/base16-concfg#about-command-line-token-colors). Have you tried to enable it by using `concfg tokencolor enable`.

**Comment by voxelv** [comment]
_cleaning up issues I've created. Closing as "stale"_
